theme: jekyll-theme-cayman

title: Cooperatiza
description: Site de apresentação do projeto de cooperatização
github:
  organizacao: https://github.com/Estaca-Inova
  atas: https://github.com/Estaca-Inova/atas-de-reuniao
  conhecimento: https://github.com/Estaca-Inova/base-de-conhecimento
  notion: https://melodic-secretary-9f4.notion.site/Aplicativo-Cooperativa-de-Diaristas-5f27a65862ae4b449c9a8e108f602b8b